# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-02 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='users',
            new_name='user',
        ),
    ]
