# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181102_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
